# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "MonitorECSXCommand"
region="eu-central-1"

[default.build.parameters]
cached = true
parallel = true
use_container = true
[default.validate.parameters]
lint = true

[default.deploy.parameters]
s3_bucket="your-artifacts-bucket-here"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
image_repositories = []
# Uncomment the below if you're using a signing profile for your lambda functions
# signing-profiles = [
#    "MonitorECSXCommand=SAMSigningProfile"
#    ]

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
